export const initialProducts = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    category: "Electronics",
    price: 999,
    stock: 45,
    status: "Active",
    description: "Latest iPhone with advanced camera system and titanium design.",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: [
      {
        id: 1,
        user: "John Doe",
        rating: 5,
        comment: "Excellent phone with amazing camera quality!",
        date: "2024-01-15",
      },
      { id: 2, user: "Jane Smith", rating: 4, comment: "Great performance but expensive.", date: "2024-01-10" },
    ],
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    category: "Electronics",
    price: 899,
    stock: 32,
    status: "Active",
    description: "Flagship Android phone with AI-powered features.",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: [
      {
        id: 3,
        user: "Mike Johnson",
        rating: 5,
        comment: "Love the AI features and display quality.",
        date: "2024-01-12",
      },
    ],
  },
  {
    id: 3,
    name: "MacBook Air M3",
    category: "Electronics",
    price: 1299,
    stock: 0,
    status: "Inactive",
    description: "Ultra-thin laptop with M3 chip for exceptional performance.",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: [
      { id: 4, user: "Sarah Wilson", rating: 5, comment: "Perfect for work and creative tasks.", date: "2024-01-08" },
    ],
  },
  {
    id: 4,
    name: "Nike Air Max",
    category: "Clothing",
    price: 120,
    stock: 78,
    status: "Active",
    description: "Comfortable running shoes with air cushioning technology.",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    reviews: [],
  },
  {
    id: 5,
    name: "Coffee Maker Pro",
    category: "Home & Garden",
    price: 199,
    stock: 23,
    status: "Active",
    description: "Professional-grade coffee maker with programmable features.",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: [{ id: 5, user: "Tom Brown", rating: 4, comment: "Makes great coffee, easy to use.", date: "2024-01-05" }],
  },
]