import {
  Shirt, Smartphone,
  Book,
  Coffee,
  Gamepad2,
  Headphones,
} from "lucide-react"

// Mock data
export const FloatingCards = [
  {
    id: 1,
    rotation: -15,
    centerX: 0,
    centerY: 0,
    finalX: -300,
    finalY: 0,
    delay: 0,
  },
  {
    id: 2,
    rotation: 10,
    centerX: 0,
    centerY: 0,
    finalX: -160,
    finalY: -20,
    delay: 0.2,
  },
  {
    id: 3,
    rotation: -8,
    centerX: 0,
    centerY: 0,
    finalX: -60,
    finalY: 15,
    delay: 0.4,
  },
  {
    id: 4,
    rotation: 12,
    centerX: 0,
    centerY: 0,
    finalX: 0,
    finalY: -10,
    delay: 0.6,
  },
  {
    id: 5,
    rotation: -20,
    centerX: 0,
    centerY: 0,
    finalX: 100,
    finalY: 20,
    delay: 0.8,
  },
  {
    id: 6,
    rotation: 15,
    centerX: 0,
    centerY: 0,
    finalX: 220,
    finalY: -15,
    delay: 1.0,
  },
  {
    id: 7,
    rotation: -5,
    centerX: 0,
    centerY: 0,
    finalX: 350,
    finalY: 5,
    delay: 1.2,
  },
];

export const trendingProducts = [
  {
    id: 1,
    name: "EcoSmart Water Bottle",
    price: "$24.99",
    originalPrice: "$34.99",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: 124,
    badge: "Trending",
    startup: "GreenTech Solutions",
  },
  {
    id: 2,
    name: "StudyBuddy Planner",
    price: "$15.99",
    originalPrice: "$19.99",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviews: 89,
    badge: "Hot",
    startup: "Campus Innovations",
  },
  {
    id: 3,
    name: "Wireless Charging Pad",
    price: "$29.99",
    originalPrice: "$39.99",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviews: 156,
    badge: "New",
    startup: "TechFlow",
  },
  {
    id: 4,
    name: "Organic Coffee Blend",
    price: "$18.99",
    originalPrice: "$24.99",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviews: 203,
    badge: "Popular",
    startup: "Bean Dreams",
  },
  {
    id: 5,
    name: "Smart Desk Organizer",
    price: "$32.99",
    originalPrice: "$42.99",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviews: 78,
    badge: "Featured",
    startup: "Workspace Pro",
  },
]

export const topPicks = [
  {
    id: 1,
    name: "Premium Laptop Stand",
    price: "$45.99",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    reviews: 234,
    startup: "ErgoTech",
    description: "Adjustable aluminum laptop stand for better posture",
  },
  {
    id: 2,
    name: "Sustainable Backpack",
    price: "$67.99",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 189,
    startup: "EcoCarry",
    description: "Made from recycled materials, perfect for students",
  },
  {
    id: 3,
    name: "Smart Study Light",
    price: "$38.99",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 145,
    startup: "BrightMind",
    description: "LED desk lamp with focus-enhancing features",
  },
  {
    id: 4,
    name: "Protein Snack Box",
    price: "$22.99",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 267,
    startup: "FuelUp",
    description: "Healthy snacks delivered to your dorm",
  },
]

export const categories = [
  { name: "Clothing", icon: Shirt, count: 156, color: "from-pink-500 to-rose-500" },
  { name: "Electronics", icon: Smartphone, count: 89, color: "from-blue-500 to-cyan-500" },
  { name: "Books & Stationery", icon: Book, count: 234, color: "from-green-500 to-emerald-500" },
  { name: "Food & Beverages", icon: Coffee, count: 78, color: "from-orange-500 to-amber-500" },
  { name: "Gaming", icon: Gamepad2, count: 45, color: "from-purple-500 to-violet-500" },
  { name: "Audio", icon: Headphones, count: 67, color: "from-indigo-500 to-blue-500" },
]
